### ISSUE TITLE
编辑会话会重新创建新的,而不是修改

### ISSUE THREAD

**Issue by Jonnyan404** [G3G4X5X6/ultimateshell#17]
**Describe the bug**
1. 编辑会话功能和新建会话功能一样了~~~
2. 仪表板的会话管理不能即时刷新信息,和菜单栏 终端-->会话管理 信息不一致.

**Desktop (please complete the following information):**
 - OS: window
 - Version: 11
 - App version: [ultimateshell_v3.55.28]

**Comment by G3G4X5X6** [comment]
1. 编辑会话功能，正常应该是这样的（自动填充相关信息），不是的话建议看看日志有没有报错：
![image](https://user-images.githubusercontent.com/87740076/156491907-01dc560f-3315-4e30-9aed-a8075ac5e771.png)

2. 会话管理的即时刷新，**下一个版本**实现（自动监控会话变动，即时刷新）
3. 下个版本应该会在3月5~3月6发布

**Comment by Jonnyan404** [comment]
不不不,编辑会话,我是仅仅修改一个 username ,其它都不更改. 
然后,保存会话,列表里就会多出一个配置.

**Comment by G3G4X5X6** [comment]
明白了，这是一个设计缺陷，使用了用户名作为会话文件名保存，修改用户名导致文件名不同，从而生成新的会话文件。
下个版本修复改问题，感谢反馈! :+1:
