### ISSUE TITLE
命令窗口字体模糊的问题

### ISSUE THREAD

**Issue by noangel2014** [G3G4X5X6/ultimateshell#22]
sftp功能有问题？ 

1.右键没反应，要选中文件或者目录才能显示右键,不能上传目录，只能选择文件，并且没反应

2.不能拖动上传

另外命令窗口字体好模糊

当前版本 3.58.33

**Comment by G3G4X5X6** [comment]
1. 右键没反应，设置的监听器的监听范围小了吧，下次调一调范围（目前来说是正常的）
2. 可以上传目录的，选中目录 -> 打开，就可以了
3. 拖动上传后面的版本再实现了
4. 命名窗口字体模糊，字体调大点？（好像不可以调，下个版本添加配置项）

**Comment by noangel2014** [comment]
感谢回复，应该不是字体大小的问题，就是字体显示比较模糊，其他软件没这个问题
本来想截图给你看下的，结果不知道为啥  办公室新装的，啥也连不上，一直提示连接失败，暂时用不了啦

**Comment by G3G4X5X6** [comment]
1. 啥也连不上，可以贴上日志看看
2. 字体模糊问题，我作为Bug康康

**Comment by G3G4X5X6** [comment]
字体模糊问题，我看了下
1. 主题：FlatArcIJTheme，下的命令行窗口
![image](https://user-images.githubusercontent.com/87740076/157581632-3df2f3aa-5c92-4367-b03e-0c6cfbc9d7c6.png)

2. 不启用主题配置时的命令行窗口
![image](https://user-images.githubusercontent.com/87740076/157581650-20fee58d-863d-4473-95c7-d208837facae.png)

也就是说，命令行窗口字体模糊，应该是因为在该主题下的配色问题。后面版本可以的话考虑命令行窗口独立配置配色或可自定义吧。目前的话，设置为别的主题试试？

**Comment by noangel2014** [comment]
[ultimateshell.log](https://github.com/G3G4X5X6/ultimateshell/files/8221953/ultimateshell.log)

**Comment by G3G4X5X6** [comment]
本地与目标的网络通信可还行？
![image](https://user-images.githubusercontent.com/87740076/157673718-8af29cb5-902b-4be9-a04e-084ffbb5cfa2.png)

**Comment by noangel2014** [comment]
说个搞笑的事情，原来是被我防火墙自动拦截网络连接了  我说怎么其他软件可以连，就这个突然连不上了

**Comment by noangel2014** [comment]
![Snipaste_2022-03-11_10-52-36](https://user-images.githubusercontent.com/23518031/157793075-74c09443-2982-4470-b399-dd42433a4ebf.jpg)

顺便截个图，确实比较糊，我装了几个客户端，就这个糊

**Comment by G3G4X5X6** [comment]
嗯嗯，确实模糊了点，这个我做过一些测试，好像字体对这个的影响还是蛮大的，但是我发现的只有宋体可以同时支持中英文而且还不会变形，后面有时间我看看怎么弄个好一点的字体，然后再看看是哪里还需要优化 😿

**Comment by noangel2014** [comment]
这个也无所谓，不影响使用，有时间再调吧，先把上传修好吧 哈哈 
![ss](https://user-images.githubusercontent.com/23518031/157812687-4ba98cf9-e943-4fd6-a914-b32285cd787c.gif)

传不了目录 ，右边窗口右键无效.  

其实现在市面上收费不收费的客户端挺多的，没必要什么功能都做，摊子太大了容易太监。建议先把基础功能做好

**Comment by G3G4X5X6** [comment]
这个目录是常规的还是快捷方式？点击这个按钮没反应吗？
![image](https://user-images.githubusercontent.com/87740076/157815203-17a9c191-6ab3-4c1b-a3c1-e0c62572de02.png)

我希望只有一种情况会太监，那就是我不用ssh连接了。建议很好，现在都是在优化和解决存在的问题了 💯

**Comment by noangel2014** [comment]
肯定是目录的，点那里也没反应

刚才我又试了下，原来已经传上去了，不过居然右边不显示，刷新菜单也没有。

![Snipaste_2022-03-12_10-36-23](https://user-images.githubusercontent.com/23518031/158000625-432531a8-aa8b-4c4e-8640-6f4a9ac30cfe.jpg)
 
SFTP功能其实蛮重要的，我建议你参考下finalshell的文件管理，已经无敌了

**Comment by G3G4X5X6** [comment]
好的
