### ISSUE TITLE
后续能否允许从ssh的config文件里导入配置呢

### ISSUE THREAD

**Issue by Ecalose** [G3G4X5X6/ultimateshell#23]
rt，就像tabby一样，可以直接读取config导入，因为有时候直接用cmd然后ssh hostname就行了

**Comment by G3G4X5X6** [comment]
怎么说？详细描述下需求？

**Comment by Ecalose** [comment]
> 怎么说？详细描述下？

就是像这样，会话管理那儿能否允许从.ssh/config里批量导入，另外字体方面能否允许选择呢？因为zsh有的主题需要等宽字体才能显示完全
![Inked图片2_LI](https://user-images.githubusercontent.com/47114714/158049469-12a869c8-2d97-4865-abcd-9678d8a3aed3.jpg)
![屏幕截图 2022-03-13 151346](https://user-images.githubusercontent.com/47114714/158049473-94bc57ea-e6c5-4653-b6a2-45f867c7dd6a.png)

**Comment by G3G4X5X6** [comment]
目前来说，字体是可以通过配置文件配置的，如下：
> 程序界面没有的配置可以看看配置文件，可能有惊喜（优先实现配置文件配置）

![image](https://user-images.githubusercontent.com/87740076/158571334-1d955ef1-2c4b-410a-bdb6-f8fc0ec9db0a.png)

我没理解错的话其实就是想要个批量导入功能？而且是会话保存在单文件的？

**Comment by Ecalose** [comment]
> 目前来说，字体是可以通过配置文件配置的，如下：
> 
> > 程序界面没有的配置可以看看配置文件，可能有惊喜（优先实现配置文件配置）
> 
> ![image](https://user-images.githubusercontent.com/87740076/158571334-1d955ef1-2c4b-410a-bdb6-f8fc0ec9db0a.png)
> 
> 我没理解错的话其实就是想要个批量导入功能？而且是会话保存在单文件的？

感谢回复，字体问题已解决，的确是需要个从.ssh/config里批量导入的功能

**Comment by G3G4X5X6** [comment]
这个可以有
